name: Pytest_conduit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Testing-Conduit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Initialising check out
        uses: actions/checkout@v2
        
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f python-tests/requirements.txt ]; then pip install -r python-tests/requirements.txt; fi
          
      - name: Install Chrome
        run: |
          sudo apt install google-chrome-stable
          
      - name: Starting Docker
        run: docker-compose up -d
      
      - name: Sleep for 84 seconds to start Docker
        run: sleep 84s
        shell: bash
        
      - name: Test with pytest
        run: |
          pytest --alluredir=allure-results
          
      - name: Get Allure History
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          
      - name: Allure Report action from Conduit
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
