name: SeleniumIDE
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'


jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
  
  SeleniumIDE:
    runs-on: ubuntu-latest
    steps:
    
    - name: install Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Selenium Side Runner
      run: |
        npm install -g selenium-side-runner
 
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install seleniumbase
      run: pip install seleniumbase

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Tests
      run: |
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" ./seleniumide-tests/registration.side
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" ./seleniumide-tests/login.side
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" ./seleniumide-tests/post.side
